### ISSUE TITLE
unittest always fail on macos with OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ssbarnea** [ansible/molecule#1549]
# Issue Type

- Bug report

# Molecule and Ansible details

```
test/unit/verifier/lint/test_yamllint.py::test_executes_catches_and_exits_return_code PASSED
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/ssbarnea/os/molecule/.tox/py27-ansible25-unit/lib/python2.7/site-packages/_pytest/main.py", line 98, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/ssbarnea/os/molecule/.tox/py27-ansible25-unit/lib/python2.7/site-packages/_pytest/main.py", line 133, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/Users/ssbarnea/os/molecule/.tox/py27-ansible25-unit/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/Users/ssbarnea/os/molecule/.tox/py27-ansible25-unit/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/ssbarnea/os/molecule/.tox/py27-ansible25-unit/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/Users/ssbarnea/os/molecule/.tox/py27-ansible25-unit/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 613, in execute
INTERNALERROR>     return _wrapped_call(hook_impl.function(*args), self.execute)
INTERNALERROR>   File "/Users/ssbarnea/os/molecule/.tox/py27-ansible25-unit/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 250, in _wrapped_call
INTERNALERROR>     wrap_controller.send(call_outcome)
INTERNALERROR>   File "/Users/ssbarnea/os/molecule/.tox/py27-ansible25-unit/lib/python2.7/site-packages/pytest_cov/plugin.py", line 228, in pytest_runtestloop
INTERNALERROR>     self.cov_controller.finish()
INTERNALERROR>   File "/Users/ssbarnea/os/molecule/.tox/py27-ansible25-unit/lib/python2.7/site-packages/pytest_cov/engine.py", line 167, in finish
INTERNALERROR>     self.cov.stop()
INTERNALERROR>   File "/Users/ssbarnea/os/molecule/.tox/py27-ansible25-unit/lib/python2.7/site-packages/coverage/control.py", line 675, in load
INTERNALERROR>     self._init()
INTERNALERROR>   File "/Users/ssbarnea/os/molecule/.tox/py27-ansible25-unit/lib/python2.7/site-packages/coverage/control.py", line 223, in _init
INTERNALERROR>     set_relative_directory()
INTERNALERROR>   File "/Users/ssbarnea/os/molecule/.tox/py27-ansible25-unit/lib/python2.7/site-packages/coverage/files.py", line 28, in set_relative_directory
INTERNALERROR>     RELATIVE_DIR = os.path.normcase(abs_file(os.curdir) + os.sep)
INTERNALERROR>   File "/Users/ssbarnea/os/molecule/.tox/py27-ansible25-unit/lib/python2.7/site-packages/coverage/files.py", line 163, in abs_file
INTERNALERROR>     path = os.path.realpath(path)
INTERNALERROR>   File "/Users/ssbarnea/os/molecule/.tox/py27-ansible25-unit/lib/python2.7/posixpath.py", line 376, in realpath
INTERNALERROR>     return abspath(path)
INTERNALERROR>   File "/Users/ssbarnea/os/molecule/.tox/py27-ansible25-unit/lib/python2.7/posixpath.py", line 364, in abspath
INTERNALERROR>     cwd = os.getcwd()
INTERNALERROR> OSError: [Errno 2] No such file or directory

============================================================================== 3 failed, 709 passed in 48.96 seconds ===============================================================================
ERROR: InvocationError for command '/Users/ssbarnea/os/molecule/.tox/py27-ansible25-unit/bin/py.test -vv --cov-report=term-missing --cov=/Users/ssbarnea/os/molecule/molecule/ --no-cov-on-fail' (exited with code 3)
_____________________________________________________________________________________________ summary ______________________________________________________________________________________________
ERROR:   py27-ansible25-unit: commands failed
TOXENV=py27-ansible25-unit tox  70.54s user 19.14s system 89% cpu 1:40.03 total
```

**Comment by webknjaz** [comment]
Hi @ssbarnea, I've fixed this bug in #1541.

Long story short, tests do `os.chdir()` to a temporary location, that location gets removed, but tests don't care to `os.chdir()` back. So cwd points to unexisting location and pytest-cov crashes when trying to `os.getcwd()`.

Ref: https://github.com/ansible/molecule/pull/1541#issuecomment-435679212

**Comment by ssbarnea** [comment]
@webknjaz Please, add bugfixed as separated PRs, it does not make sense to clutter the one about enabling Travis with all these, making extreamly hard to review it.  Ideally the travis one should only add one file, the `.travis.yml` one.

Feel free to add me as reviewer for PRs as I have a high interest in making molecule better.

**Comment by webknjaz** [comment]
Sorry, this one stays in that PR for a very simple reason: we've agreed to not merge anything until Travis CI is up and running (and enforced). So even if I separate it, it won't be merged.
Also, it is tightly coupled with that PR as without this patch it's failing, so we'd have to include it there anyway. Essentially, that PR is about making CI green, not just enabling it.

P.S. We can only add reviewers from org, GH won't let add others :)

**Comment by gundalow** [comment]
Fix for this has been split into a separate PR https://github.com/ansible/molecule/pull/1560 reviews welcome
