### ISSUE TITLE
Running `molecule converge` returned TypeError: 'NoneType' object is not iterable other=None

### ISSUE THREAD

**Issue by zachzeid** [ansible/molecule#1621]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.7.4
molecule, version 2.19.0
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

# Desired Behavior
Desired behavior is to run `converge` against ansible playbooks.

# Actual Behaviour
```python-traceback
 Traceback (most recent call last):
  File "/Users/user/github/ansible.php/.venv/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/molecule/command/check.py", line 95, in check
    base.get_configs(args, command_args), scenario_name)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/molecule/command/base.py", line 121, in get_configs
    ) for c in glob.glob(MOLECULE_GLOB)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/molecule/config.py", line 61, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/molecule/config.py", line 104, in __init__
    self.config = self._get_config()
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/molecule/config.py", line 277, in _get_config
    return self._combine(keep_string=MOLECULE_KEEP_STRING)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/molecule/config.py", line 320, in _combine
    util.safe_load(interpolated_config))
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/molecule/util.py", line 298, in merge_dicts
    anyconfig.merge(a, b, ac_merge=MERGE_STRATEGY)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/anyconfig/dicts.py", line 294, in merge
    _update_fn(self, other, key, **options)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/anyconfig/dicts.py", line 234, in _update_with_merge
    merge(self[key], val, merge_lists=merge_lists, **options)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/anyconfig/dicts.py", line 294, in merge
    _update_fn(self, other, key, **options)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/anyconfig/dicts.py", line 234, in _update_with_merge
    merge(self[key], val, merge_lists=merge_lists, **options)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/anyconfig/dicts.py", line 300, in merge
    raise type(exc)("%s other=%r" % (str(exc), other))
TypeError: 'NoneType' object is not iterable other=None
RAW Paste Data

molecule check
Traceback (most recent call last):
  File "/Users/user/github/ansible.php/.venv/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/molecule/command/check.py", line 95, in check
    base.get_configs(args, command_args), scenario_name)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/molecule/command/base.py", line 121, in get_configs
    ) for c in glob.glob(MOLECULE_GLOB)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/molecule/config.py", line 61, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/molecule/config.py", line 104, in __init__
    self.config = self._get_config()
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/molecule/config.py", line 277, in _get_config
    return self._combine(keep_string=MOLECULE_KEEP_STRING)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/molecule/config.py", line 320, in _combine
    util.safe_load(interpolated_config))
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/molecule/util.py", line 298, in merge_dicts
    anyconfig.merge(a, b, ac_merge=MERGE_STRATEGY)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/anyconfig/dicts.py", line 294, in merge
    _update_fn(self, other, key, **options)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/anyconfig/dicts.py", line 234, in _update_with_merge
    merge(self[key], val, merge_lists=merge_lists, **options)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/anyconfig/dicts.py", line 294, in merge
    _update_fn(self, other, key, **options)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/anyconfig/dicts.py", line 234, in _update_with_merge
    merge(self[key], val, merge_lists=merge_lists, **options)
  File "/Users/user/github/ansible.php/.venv/lib/python2.7/site-packages/anyconfig/dicts.py", line 300, in merge
    raise type(exc)("%s other=%r" % (str(exc), other))
TypeError: 'NoneType' object is not iterable other=None
 ```
Returns TypeError: 'NoneType object is not iterable other=None
Removing molecule and reinstalling results in the same error
Recreated virtualenv results in the same error.

**Comment by webknjaz** [comment]
Could you please also post a minimum reproducible example for this?
And share the output of `pip freeze` for the env where it fails vs. the env where it doesn't.

**Comment by webknjaz** [comment]
Oh and JFYI currently Molecule targets roles, not playbooks.

**Comment by zachzeid** [comment]
Deleting the directory and pulling it down resolved this issue.  Sorry and thank you!

**Comment by theDevilsVoice** [comment]
> Deleting the directory and pulling it down resolved this issue. Sorry and thank you!

Maybe this will help someone else...

I was experiencing this issue as well. Was able to resolve it by correcting indentation in molecule.yml
