### ISSUE TITLE
Flake8 3.5.0 has a 'no attribute' error

### ISSUE THREAD

**Issue by hylaride** [ansible/molecule#1627]
Flake8 has a [bug](https://gitlab.com/pycqa/flake8/issues/406) that causes an error in certain situations.  FYI, it's fixed in flake8 3.6.0 (molecule 2.19.0 requires 3.5.0) and force-installing it fixes my issue.

# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.7.4
  config file = /Users/chylarides/.ansible.cfg
  configured module search path = ['/Users/chylarides/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/chylarides/.pyenv/versions/3.6.3/envs/ansible-vault/lib/python3.6/site-packages/ansible
  executable location = /Users/chylarides/.pyenv/versions/3.6.3/envs/ansible-vault/bin/ansible
  python version = 3.6.3 (default, Dec  5 2018, 16:17:59) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
molecule, version 2.19.0
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

Flake8 tests should pass

# Actual Behaviour

```Traceback (most recent call last):
  File "/Users/chylarides/.pyenv/versions/3.6.3/envs/ansible-vault/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2299, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'pycodestyle' has no attribute 'break_around_binary_operator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chylarides/.pyenv/versions/3.6.3/envs/ansible-vault/lib/python3.6/site-packages/flake8/plugins/manager.py", line 178, in load_plugin
    self._load(verify_requirements)
  File "/Users/chylarides/.pyenv/versions/3.6.3/envs/ansible-vault/lib/python3.6/site-packages/flake8/plugins/manager.py", line 150, in _load
    self._plugin = resolve()
  File "/Users/chylarides/.pyenv/versions/3.6.3/envs/ansible-vault/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2301, in resolve
    raise ImportError(str(exc))
ImportError: module 'pycodestyle' has no attribute 'break_around_binary_operator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chylarides/.pyenv/versions/3.6.3/envs/ansible-vault/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/Users/chylarides/.pyenv/versions/3.6.3/envs/ansible-vault/lib/python3.6/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/Users/chylarides/.pyenv/versions/3.6.3/envs/ansible-vault/lib/python3.6/site-packages/flake8/main/application.py", line 396, in run
    self._run(argv)
  File "/Users/chylarides/.pyenv/versions/3.6.3/envs/ansible-vault/lib/python3.6/site-packages/flake8/main/application.py", line 383, in _run
    self.initialize(argv)
  File "/Users/chylarides/.pyenv/versions/3.6.3/envs/ansible-vault/lib/python3.6/site-packages/flake8/main/application.py", line 365, in initialize
    self.find_plugins()
  File "/Users/chylarides/.pyenv/versions/3.6.3/envs/ansible-vault/lib/python3.6/site-packages/flake8/main/application.py", line 191, in find_plugins
    self.check_plugins.load_plugins()
  File "/Users/chylarides/.pyenv/versions/3.6.3/envs/ansible-vault/lib/python3.6/site-packages/flake8/plugins/manager.py", line 423, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/Users/chylarides/.pyenv/versions/3.6.3/envs/ansible-vault/lib/python3.6/site-packages/flake8/plugins/manager.py", line 311, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/Users/chylarides/.pyenv/versions/3.6.3/envs/ansible-vault/lib/python3.6/site-packages/flake8/plugins/manager.py", line 421, in load_plugin
    return plugin.load_plugin()
  File "/Users/chylarides/.pyenv/versions/3.6.3/envs/ansible-vault/lib/python3.6/site-packages/flake8/plugins/manager.py", line 186, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.break_around_binary_operator" due to module 'pycodestyle' has no attribute 'break_around_binary_operator'.```

**Comment by hylaride** [comment]
bah! I see there's already a PR for this.  Closing.
