### ISSUE TITLE
Molecule Lint (Flake8) cannot import name ConverterMapping

### ISSUE THREAD

**Issue by osulli** [ansible/molecule#1718]
# Issue Type

- Bug report

# Molecule and Ansible details

```
oscar@infinitum:~/code/devops/ansible-roles/groups$ ansible --version
ansible 2.7.6
  config file = None
  configured module search path = [u'/home/oscar/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/oscar/.local/lib/python2.7/site-packages/ansible
  executable location = /home/oscar/.local/bin/ansible
  python version = 2.7.15+ (default, Oct  2 2018, 22:12:08) [GCC 8.2.0]

oscar@infinitum:~/code/devops/ansible-roles/groups$ molecule --version
molecule, version 2.19.0
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

Detail any linters or test runners used:

# Desired Behavior

I run `molecule lint` or `molecule test` and the `lint` process runs without software issue.

# Actual Behaviour

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.
```
oscar@infinitum:~/code/devops/ansible-roles/groups$ molecule lint
--> Validating schema /home/oscar/code/devops/ansible-roles/groups/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix
    
└── default
    └── lint
    
--> Scenario: 'default'
--> Action: 'lint'
--> Executing Yamllint on files found in /home/oscar/code/devops/ansible-roles/groups/...
Lint completed successfully.
--> Executing Flake8 on files found in /home/oscar/code/devops/ansible-roles/groups/molecule/default/tests/...
Traceback (most recent call last):
  File "/home/oscar/.local/bin/flake8", line 7, in <module>
    from flake8.main.cli import main
  File "/home/oscar/.local/lib/python2.7/site-packages/flake8/main/cli.py", line 2, in <module>
    from flake8.main import application
  File "/home/oscar/.local/lib/python2.7/site-packages/flake8/main/application.py", line 14, in <module>
    from flake8.main import options
  File "/home/oscar/.local/lib/python2.7/site-packages/flake8/main/options.py", line 4, in <module>
    from flake8.main import vcs
  File "/home/oscar/.local/lib/python2.7/site-packages/flake8/main/vcs.py", line 4, in <module>
    from flake8.main import mercurial
  File "/home/oscar/.local/lib/python2.7/site-packages/flake8/main/mercurial.py", line 7, in <module>
    import configparser
  File "/home/oscar/.local/lib/python2.7/site-packages/configparser.py", line 12, in <module>
    from backports.configparser import (
ImportError: cannot import name ConverterMapping
```

Debug on:

```
oscar@infinitum:~/code/devops/ansible-roles/groups$ molecule --debug lint
--> Validating schema /home/oscar/code/devops/ansible-roles/groups/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix
    
└── default
    └── lint
    
--> Scenario: 'default'
--> Action: 'lint'
--> Executing Yamllint on files found in /home/oscar/code/devops/ansible-roles/groups/...
DEBUG: ANSIBLE ENVIRONMENT
--- {}

DEBUG: MOLECULE ENVIRONMENT
---
MOLECULE_DEBUG: 'True'
MOLECULE_DEPENDENCY_NAME: galaxy
MOLECULE_DRIVER_NAME: docker
MOLECULE_ENV_FILE: /home/oscar/code/devops/ansible-roles/groups/.env.yml
MOLECULE_EPHEMERAL_DIRECTORY: /tmp/molecule/groups/default
MOLECULE_FILE: /home/oscar/code/devops/ansible-roles/groups/molecule/default/molecule.yml
MOLECULE_INSTANCE_CONFIG: /tmp/molecule/groups/default/instance_config.yml
MOLECULE_INVENTORY_FILE: /tmp/molecule/groups/default/ansible_inventory.yml
MOLECULE_LINT_NAME: yamllint
MOLECULE_PROJECT_DIRECTORY: /home/oscar/code/devops/ansible-roles/groups
MOLECULE_PROVISIONER_LINT_NAME: ansible-lint
MOLECULE_PROVISIONER_NAME: ansible
MOLECULE_SCENARIO_DIRECTORY: /home/oscar/code/devops/ansible-roles/groups/molecule/default
MOLECULE_SCENARIO_NAME: default
MOLECULE_VERIFIER_LINT_NAME: flake8
MOLECULE_VERIFIER_NAME: testinfra
MOLECULE_VERIFIER_TEST_DIRECTORY: /home/oscar/code/devops/ansible-roles/groups/molecule/default/tests

DEBUG: SHELL REPLAY
MOLECULE_DEBUG=True MOLECULE_DEPENDENCY_NAME=galaxy MOLECULE_DRIVER_NAME=docker MOLECULE_ENV_FILE=/home/oscar/code/devops/ansible-roles/groups/.env.yml MOLECULE_EPHEMERAL_DIRECTORY=/tmp/molecule/groups/default MOLECULE_FILE=/home/oscar/code/devops/ansible-roles/groups/molecule/default/molecule.yml MOLECULE_INSTANCE_CONFIG=/tmp/molecule/groups/default/instance_config.yml MOLECULE_INVENTORY_FILE=/tmp/molecule/groups/default/ansible_inventory.yml MOLECULE_LINT_NAME=yamllint MOLECULE_PROJECT_DIRECTORY=/home/oscar/code/devops/ansible-roles/groups MOLECULE_PROVISIONER_LINT_NAME=ansible-lint MOLECULE_PROVISIONER_NAME=ansible MOLECULE_SCENARIO_DIRECTORY=/home/oscar/code/devops/ansible-roles/groups/molecule/default MOLECULE_SCENARIO_NAME=default MOLECULE_VERIFIER_LINT_NAME=flake8 MOLECULE_VERIFIER_NAME=testinfra MOLECULE_VERIFIER_TEST_DIRECTORY=/home/oscar/code/devops/ansible-roles/groups/molecule/default/tests

DEBUG: COMMAND
/home/oscar/.local/bin/yamllint -s /home/oscar/code/devops/ansible-roles/groups/handlers/main.yml /home/oscar/code/devops/ansible-roles/groups/molecule/default/playbook.yml /home/oscar/code/devops/ansible-roles/groups/molecule/default/molecule.yml /home/oscar/code/devops/ansible-roles/groups/vars/main.yml /home/oscar/code/devops/ansible-roles/groups/defaults/main.yml /home/oscar/code/devops/ansible-roles/groups/meta/main.yml /home/oscar/code/devops/ansible-roles/groups/tasks/main.yml

Lint completed successfully.
--> Executing Flake8 on files found in /home/oscar/code/devops/ansible-roles/groups/molecule/default/tests/...
DEBUG: ANSIBLE ENVIRONMENT
--- {}

DEBUG: MOLECULE ENVIRONMENT
---
MOLECULE_DEBUG: 'True'
MOLECULE_DEPENDENCY_NAME: galaxy
MOLECULE_DRIVER_NAME: docker
MOLECULE_ENV_FILE: /home/oscar/code/devops/ansible-roles/groups/.env.yml
MOLECULE_EPHEMERAL_DIRECTORY: /tmp/molecule/groups/default
MOLECULE_FILE: /home/oscar/code/devops/ansible-roles/groups/molecule/default/molecule.yml
MOLECULE_INSTANCE_CONFIG: /tmp/molecule/groups/default/instance_config.yml
MOLECULE_INVENTORY_FILE: /tmp/molecule/groups/default/ansible_inventory.yml
MOLECULE_LINT_NAME: yamllint
MOLECULE_PROJECT_DIRECTORY: /home/oscar/code/devops/ansible-roles/groups
MOLECULE_PROVISIONER_LINT_NAME: ansible-lint
MOLECULE_PROVISIONER_NAME: ansible
MOLECULE_SCENARIO_DIRECTORY: /home/oscar/code/devops/ansible-roles/groups/molecule/default
MOLECULE_SCENARIO_NAME: default
MOLECULE_VERIFIER_LINT_NAME: flake8
MOLECULE_VERIFIER_NAME: testinfra
MOLECULE_VERIFIER_TEST_DIRECTORY: /home/oscar/code/devops/ansible-roles/groups/molecule/default/tests

DEBUG: SHELL REPLAY
MOLECULE_DEBUG=True MOLECULE_DEPENDENCY_NAME=galaxy MOLECULE_DRIVER_NAME=docker MOLECULE_ENV_FILE=/home/oscar/code/devops/ansible-roles/groups/.env.yml MOLECULE_EPHEMERAL_DIRECTORY=/tmp/molecule/groups/default MOLECULE_FILE=/home/oscar/code/devops/ansible-roles/groups/molecule/default/molecule.yml MOLECULE_INSTANCE_CONFIG=/tmp/molecule/groups/default/instance_config.yml MOLECULE_INVENTORY_FILE=/tmp/molecule/groups/default/ansible_inventory.yml MOLECULE_LINT_NAME=yamllint MOLECULE_PROJECT_DIRECTORY=/home/oscar/code/devops/ansible-roles/groups MOLECULE_PROVISIONER_LINT_NAME=ansible-lint MOLECULE_PROVISIONER_NAME=ansible MOLECULE_SCENARIO_DIRECTORY=/home/oscar/code/devops/ansible-roles/groups/molecule/default MOLECULE_SCENARIO_NAME=default MOLECULE_VERIFIER_LINT_NAME=flake8 MOLECULE_VERIFIER_NAME=testinfra MOLECULE_VERIFIER_TEST_DIRECTORY=/home/oscar/code/devops/ansible-roles/groups/molecule/default/tests

DEBUG: COMMAND
/home/oscar/.local/bin/flake8 /home/oscar/code/devops/ansible-roles/groups/molecule/default/tests/test_groups.py

Traceback (most recent call last):
  File "/home/oscar/.local/bin/flake8", line 7, in <module>
    from flake8.main.cli import main
  File "/home/oscar/.local/lib/python2.7/site-packages/flake8/main/cli.py", line 2, in <module>
    from flake8.main import application
  File "/home/oscar/.local/lib/python2.7/site-packages/flake8/main/application.py", line 14, in <module>
    from flake8.main import options
  File "/home/oscar/.local/lib/python2.7/site-packages/flake8/main/options.py", line 4, in <module>
    from flake8.main import vcs
  File "/home/oscar/.local/lib/python2.7/site-packages/flake8/main/vcs.py", line 4, in <module>
    from flake8.main import mercurial
  File "/home/oscar/.local/lib/python2.7/site-packages/flake8/main/mercurial.py", line 7, in <module>
    import configparser
  File "/home/oscar/.local/lib/python2.7/site-packages/configparser.py", line 12, in <module>
    from backports.configparser import (
```

- Attempted `pip uninstall`
- `pip-purge` pip tool
- `apt purge python*`
- reinstall `Ubuntu 18.10 LTS`

Please help :)

**Comment by osulli** [comment]
> :scream:
:scream: :sob:

**Comment by osulli** [comment]
It was very clearly a local config issue. 

I was using python2.7/pip to install.

I did the following:

- `sudo rm -rf /usr/lib/python2.7/dist-packages`
- `pip install pip-purge && pip-purge`
- `sudo apt purge python-pip`
- `sudo apt isntall python3-pip`
- `pip3 install ansible molecule docker --no-cache-dir`

Working just fine with **pip3**!
