### ISSUE TITLE
2.22rc1: flake8 not found

### ISSUE THREAD

**Issue by bjornmagnusson** [ansible/molecule#2094]
Molecule fails to run linter, due to flake8 not found

# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version && molecule --version
docker run --rm se-artif-prd.infinera.com/docker/ansible/molecule:2.22rc1 molecule --version
molecule, version 2.22rc1
docker run --rm se-artif-prd.infinera.com/docker/ansible/molecule:2.22rc1 ansible --version
ansible 2.8.0
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, May 11 2019, 02:00:41) [GCC 8.3.0]
```

```
---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: False
platforms:
  - name: centos7
    image: centos:7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: False
scenario:
  name: default
verifier:
  name: testinfra
  options:
    junit-xml: junit.xml
  lint:
    name: flake8

```

Molecule installation method (one of):

- docker

Ansible installation method (one of):

- OS package

Detail any linters or test runners used:

# Desired Behavior

Playbook and tests should run without errors

# Actual Behaviour

```
00:02:52.619  Status: Downloaded newer image for se-artif-prd.infinera.com/docker/ansible/molecule:2.22rc1
00:02:54.311  --> Validating schema /tmp/ansible/molecule/default/molecule.yml.
00:02:54.659  Validation completed successfully.
00:02:54.659  --> Test matrix
00:02:54.659      
00:02:54.659  └── default
00:02:54.659      ├── lint
00:02:54.659      ├── dependency
00:02:54.659      ├── cleanup
00:02:54.659      ├── destroy
00:02:54.659      ├── syntax
00:02:54.659      ├── create
00:02:54.659      ├── prepare
00:02:54.659      ├── converge
00:02:54.659      ├── idempotence
00:02:54.659      ├── side_effect
00:02:54.659      ├── verify
00:02:54.659      ├── cleanup
00:02:54.659      └── destroy
00:02:54.659      
00:02:54.659  --> Scenario: 'default'
00:02:54.659  --> Action: 'lint'
00:02:54.659  Skipping, lint is disabled.
00:02:54.659  Traceback (most recent call last):
00:02:54.659    File "/usr/local/bin/molecule", line 10, in <module>
00:02:54.659      sys.exit(main())
00:02:54.659    File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
00:02:54.659      return self.main(*args, **kwargs)
00:02:54.659    File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
00:02:54.659      rv = self.invoke(ctx)
00:02:54.659    File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
00:02:54.659      return _process_result(sub_ctx.command.invoke(sub_ctx))
00:02:54.659    File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
00:02:54.659      return ctx.invoke(self.callback, **ctx.params)
00:02:54.659    File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
00:02:54.659      return callback(*args, **kwargs)
00:02:54.659    File "/usr/local/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
00:02:54.659      return f(get_current_context(), *args, **kwargs)
00:02:54.659    File "/usr/local/lib/python3.7/site-packages/molecule/command/test.py", line 126, in test
00:02:54.659      base.execute_cmdline_scenarios(scenario_name, args, command_args)
00:02:54.659    File "/usr/local/lib/python3.7/site-packages/molecule/command/base.py", line 100, in execute_cmdline_scenarios
00:02:54.659      execute_scenario(scenario)
00:02:54.659    File "/usr/local/lib/python3.7/site-packages/molecule/command/base.py", line 140, in execute_scenario
00:02:54.659      execute_subcommand(scenario.config, action)
00:02:54.659    File "/usr/local/lib/python3.7/site-packages/molecule/command/base.py", line 127, in execute_subcommand
00:02:54.659      return command(config).execute()
00:02:54.659    File "/usr/local/lib/python3.7/site-packages/molecule/command/lint.py", line 80, in execute
00:02:54.659      l.execute()
00:02:54.659    File "/usr/local/lib/python3.7/site-packages/molecule/verifier/lint/flake8.py", line 119, in execute
00:02:54.659      self.bake()
00:02:54.659    File "/usr/local/lib/python3.7/site-packages/molecule/verifier/lint/flake8.py", line 100, in bake
00:02:54.659      self._flake8_command = sh.flake8.bake(
00:02:54.659    File "/usr/local/lib/python3.7/site-packages/sh.py", line 3349, in __getattr__
00:02:54.659      return self.__env[name]
00:02:54.659    File "/usr/local/lib/python3.7/site-packages/sh.py", line 3226, in __getitem__
00:02:54.659      raise CommandNotFound(k)
00:02:54.659  sh.CommandNotFound: flake8
```

molecule config:
```
---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  enabled: False
platforms:
  - name: centos7
    image: centos:7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: False
scenario:
  name: default
verifier:
  name: testinfra
  options:
    junit-xml: junit.xml
  lint:
    name: flake8
```

**Comment by ssbarnea** [comment]
I am not sure if this is a real bug as number of linters can be huge and it does not make sense for molecule itself to install all of them. You can easily avoid it by adding flake8 to your depencies.

I will wait for other cores comments in order to decide if we should install it or close it as a non-bug.

**Comment by themr0c** [comment]
As testinfra is the default linter, I understand that it's expected to have it installed in the Docker image, that should be usable out of the box.

**Comment by bjornmagnusson** [comment]
I would consider this a breaking change for the docker image packaging, and I could not find any information regarding this change in the release notes.

As a comparison (working with 2.20):
```
docker container run --rm quay.io/ansible/molecule:2.20 which flake8
/usr/local/bin/flake8
```
