### ISSUE TITLE
ConfigDoesNotExistException

### ISSUE THREAD

**Issue by flazzarini** [ansible/molecule#2178]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.8.2
  config file = /home/users/frank/workspace/ansible/ansible.cfg
  configured module search path = ['/home/users/frank/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/users/frank/.local/lib/python3.5/site-packages/ansible
  executable location = /home/users/frank/.local/bin/ansible
  python version = 3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609]
molecule, version 2.22rc3
```

Molecule installation method (one of):

- pip (user install)

Ansible installation method (one of):

- pip (user install)

# Desired Behavior

Create new ansible role using ``molecule init role r foobar``

# Actual Behaviour

```
$ molecule init role -r foobar
--> Initializing new role foobar...
Traceback (most recent call last):
  File "/home/users/frank/.local/bin/molecule", line 10, in <module>
    sys.exit(main())
  File "/home/users/frank/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/users/frank/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/users/frank/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/users/frank/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/users/frank/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/users/frank/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/users/frank/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/users/frank/.local/lib/python3.5/site-packages/molecule/command/init/role.py", line 160, in role
    r.execute()
  File "/home/users/frank/.local/lib/python3.5/site-packages/molecule/command/init/role.py", line 80, in execute
    role_directory)
  File "/home/users/frank/.local/lib/python3.5/site-packages/molecule/command/init/base.py", line 64, in _process_templates
    no_input=True,
  File "/home/users/frank/.local/lib/python3.5/site-packages/cookiecutter/main.py", line 54, in cookiecutter
    default_config=default_config,
  File "/home/users/frank/.local/lib/python3.5/site-packages/cookiecutter/config.py", line 124, in get_user_config
    return get_config(env_config_file)
  File "/home/users/frank/.local/lib/python3.5/site-packages/cookiecutter/config.py", line 64, in get_config
    raise ConfigDoesNotExistException
cookiecutter.exceptions.ConfigDoesNotExistException
```

Please note I have a local ``~/.cookiecutterrc`` file.

```
default_context:
    full_name: "Frank Lazzarini"
    email: "<obfuscated>"
abbreviations:
    py: <obfuscated_url>
```

**Comment by decentral1se** [comment]
That looks like a cookiecutter bug and nothing to do with Molecule?

**Comment by flazzarini** [comment]
Hi there this bug can be closed, in the environment I've tested this I've had the Environment Variable ``COOKIECUTTER_CONFIG`` set to a file which didn't exists anymore.

Removing the env variable made cookiecutter default back to `~/.cookiecutterrc`.
