### ISSUE TITLE
CI: 'SpecifierSet' object has no attribute 'split'

### ISSUE THREAD

**Issue by decentral1se** [ansible/molecule#2350]
Looks like some sort of pip/setuptools issue related to specifiers (>,<,>=,...)

> (.venv) ➜  molecule (master) ✔ pip show setuptools | grep -i version
> Version: 41.4.0
> (.venv) ➜  molecule (master) ✔ pip show pip | grep -i version 
> Version: 19.2.3

```
(.venv) ➜  molecule (master) ✔ pip install -e .      
Obtaining file:///home/decentral1se/hacking/molecule
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /home/decentral1se/hacking/molecule/.venv/bin/python /home/decentral1se/hacking/molecule/.venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp1cijsh20
         cwd: /home/decentral1se/hacking/molecule
    Complete output (28 lines):
    Traceback (most recent call last):
      File "/home/decentral1se/hacking/molecule/.venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/home/decentral1se/hacking/molecule/.venv/lib/python3.7/site-packages/pip/(.venv) ➜  molecule (master) ✔ pip install -e .                    
Obtaining file:///home/decentral1se/hacking/molecule
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /home/decentral1se/hacking/molecule/.venv/bin/python /home/decentral1se/hacking/molecule/.venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp98lvx227
         cwd: /home/decentral1se/hacking/molecule
    Complete output (28 lines):
    Traceback (most recent call last):
      File "/home/decentral1se/hacking/molecule/.venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
        main()
      File "/home/decentral1se/hacking/molecule/.venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/decentral1se/hacking/molecule/.venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 69, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-701d0led/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 156, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-701d0led/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 350, in <module>
        __name__ == '__main__' and setuptools.setup(**setup_params)
      File "/tmp/pip-build-env-701d0led/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/decentral1se/.pyenv/versions/3.7.2/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-build-env-701d0led/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 447, in __init__
        k: v for k, v in attrs.items()
      File "/home/decentral1se/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py", line 292, in __init__
        self.finalize_options()
      File "/tmp/pip-build-env-701d0led/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 735, in finalize_options
        ep.load()(self, ep.name, value)
      File "/tmp/pip-build-env-701d0led/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 291, in check_specifier
        packaging.specifiers.SpecifierSet(value)
      File "/tmp/pip-build-env-701d0led/overlay/lib/python3.7/site-packages/setuptools/_vendor/packaging/specifiers.py", line 594, in __init__
        specifiers = [s.strip() for s in specifiers.split(",") if s.strip()]
    AttributeError: 'SpecifierSet' object has no attribute 'split'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/decentral1se/hacking/molecule/.venv/bin/python /home/decentral1se/hacking/molecule/.venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp98lvx227 Check the logs for full command output.
```

**Comment by decentral1se** [comment]
Temporary fix is out @ https://github.com/ansible/molecule/pull/2351 :fire_engine:

**Comment by ssbarnea** [comment]
This seems to be the same issue I reported few minutes ago on https://github.com/ansible/ansible-lint/issues/590

**Comment by ssbarnea** [comment]
This was fixed by https://github.com/ssbarnea/molecule/commit/c1d0303cbf88038eaa428fc469ff4225f4cbb13e
