### ISSUE TITLE
 AttributeError: 'AnsibleUnicode' object has no attribute 'get'

### ISSUE THREAD

**Issue by training3** [ansible/molecule#2470]
# Molecule and Ansible details
```
ansible --version && molecule --version
ansible 2.9.2 config file = None configured module search path = ['/home/testuser/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules'] ansible python module location = /home/testuser/venv/lib/python3.6/site-packages/ansible executable location = /home/testuser/venv/bin/ansible python version = 3.6.9 (default, Nov 7 2019, 10:44:02) [GCC 8.3.0] molecule, version 2.22 
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- OS package

Detail any linters or test runners used:

# Desired Behavior
ansible-lint lints playbook without exceptions.
# Actual Behaviour
```
molecule test
--> Validating schema /home/testuser/testrole/testuser/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix

└── default
    ├── lint
    ├── dependency
    ├── cleanup
    ├── destroy
    ├── syntax
    ├── create
    ├── prepare
    ├── converge
    ├── idempotence
    ├── side_effect
    ├── verify
    ├── cleanup
    └── destroy

--> Scenario: 'default'
--> Action: 'lint'
--> Executing Yamllint on files found in /home/testuser/testrole/testuser/...
Lint completed successfully.
--> Executing Flake8 on files found in /home/testuser/testrole/testuser/molecule/default/tests/...
Lint completed successfully.
-> Executing Ansible Lint on /home/testuser/testrole/testuser/molecule/default/playbook.yml...
Traceback (most recent call last):
  File "/home/testuser/my_env/bin/ansible-lint", line 11, in <module>
    sys.exit(main())
  File "/home/testuser/my_env/lib/python3.6/site-packages/ansiblelint/__main__.py", line 187, in main
    matches.extend(runner.run())
  File "/home/testuser/my_env/lib/python3.6/site-packages/ansiblelint/__init__.py", line 287, in run
    skip_list=self.skip_list))
  File "/home/testuser/my_env/lib/python3.6/site-packages/ansiblelint/__init__.py", line 177, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File "/home/testuser/my_env/lib/python3.6/site-packages/ansiblelint/__init__.py", line 87, in matchtasks
    yaml = ansiblelint.utils.append_skipped_rules(yaml, text, file['type'])
  File "/home/testuser/my_env/lib/python3.6/site-packages/ansiblelint/utils.py", line 596, in append_skipped_rules
    yaml_skip = _append_skipped_rules(pyyaml_data, file_text, file_type)
  File "/home/testuser/my_env/lib/python3.6/site-packages/ansiblelint/utils.py", line 635, in _append_skipped_rules
    if pyyaml_task.get('name') != ruamel_task.get('name'):
AttributeError: 'AnsibleUnicode' object has no attribute 'get'
An error occurred during the test sequence action: 'lint'. Cleaning up.
```
# Output of module test --debug
```
 molecule --debug test
--> Validating schema /home/testuser/testrole/postgres/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix

└── default
    ├── lint
    ├── dependency
    ├── cleanup
    ├── destroy
    ├── syntax
    ├── create
    ├── prepare
    ├── converge
    ├── idempotence
    ├── side_effect
    ├── verify
    ├── cleanup
    └── destroy

--> Scenario: 'default'
--> Action: 'lint'
--> Executing Yamllint on files found in /home/testuser/testrole/postgres/...
DEBUG: ANSIBLE ENVIRONMENT
--- {}

DEBUG: MOLECULE ENVIRONMENT
---
MOLECULE_DEBUG: 'True'
MOLECULE_DEPENDENCY_NAME: galaxy
MOLECULE_DRIVER_NAME: docker
MOLECULE_ENV_FILE: /home/testuser/testrole/postgres/.env.yml
MOLECULE_EPHEMERAL_DIRECTORY: /home/testuser/.cache/molecule/postgres/default
MOLECULE_FILE: /home/testuser/testrole/postgres/molecule/default/molecule.yml
MOLECULE_INSTANCE_CONFIG: /home/testuser/.cache/molecule/postgres/default/instance_config.yml
MOLECULE_INVENTORY_FILE: /home/testuser/.cache/molecule/postgres/default/inventory/ansible_inventory.yml
MOLECULE_LINT_NAME: yamllint
MOLECULE_PROJECT_DIRECTORY: /home/testuser/testrole/postgres
MOLECULE_PROVISIONER_LINT_NAME: ansible-lint
MOLECULE_PROVISIONER_NAME: ansible
MOLECULE_SCENARIO_DIRECTORY: /home/testuser/testrole/postgres/molecule/default
MOLECULE_SCENARIO_NAME: default
MOLECULE_STATE_FILE: /home/testuser/.cache/molecule/postgres/default/state.yml
MOLECULE_VERIFIER_LINT_NAME: flake8
MOLECULE_VERIFIER_NAME: testinfra
MOLECULE_VERIFIER_TEST_DIRECTORY: /home/testuser/testrole/postgres/molecule/default/tests

DEBUG: SHELL REPLAY
MOLECULE_DEBUG=True MOLECULE_DEPENDENCY_NAME=galaxy MOLECULE_DRIVER_NAME=docker MOLECULE_ENV_FILE=/home/testuser/testrole/postgres/.env.yml MOLECULE_EPHEMERAL_DIRECTORY=/home/testuser/.cache/molecule/postgres/default MOLECULE_FILE=/home/testuser/testrole/postgres/molecule/default/molecule.yml MOLECULE_INSTANCE_CONFIG=/home/testuser/.cache/molecule/postgres/default/instance_config.yml MOLECULE_INVENTORY_FILE=/home/testuser/.cache/molecule/postgres/default/inventory/ansible_inventory.yml MOLECULE_LINT_NAME=yamllint MOLECULE_PROJECT_DIRECTORY=/home/testuser/testrole/postgres MOLECULE_PROVISIONER_LINT_NAME=ansible-lint MOLECULE_PROVISIONER_NAME=ansible MOLECULE_SCENARIO_DIRECTORY=/home/testuser/testrole/postgres/molecule/default MOLECULE_SCENARIO_NAME=default MOLECULE_STATE_FILE=/home/testuser/.cache/molecule/postgres/default/state.yml MOLECULE_VERIFIER_LINT_NAME=flake8 MOLECULE_VERIFIER_NAME=testinfra MOLECULE_VERIFIER_TEST_DIRECTORY=/home/testuser/testrole/postgres/molecule/default/tests

DEBUG: COMMAND
/home/testuser/venv/bin/yamllint -s /home/testuser/testrole/postgres/defaults/main.yml /home/testuser/testrole/postgres/files/main.yml /home/testuser/testrole/postgres/handlers/main.yml /home/testuser/testrole/postgres/meta/main.yml /home/testuser/testrole/postgres/molecule/default/molecule.yml /home/testuser/testrole/postgres/molecule/default/playbook.yml /home/testuser/testrole/postgres/molecule/default/prepare.yml /home/testuser/testrole/postgres/molecule/default/requirements.yml /home/testuser/testrole/postgres/tasks/backup.yml /home/testuser/testrole/postgres/tasks/centos_vars.yml /home/testuser/testrole/postgres/tasks/include_vaults.yml /home/testuser/testrole/postgres/tasks/init.yml /home/testuser/testrole/postgres/tasks/install.yml /home/testuser/testrole/postgres/tasks/install_centos_packages.yml /home/testuser/testrole/postgres/tasks/main.yml /home/testuser/testrole/postgres/tasks/redhat_vars.yml /home/testuser/testrole/postgres/vars/main.yml

Lint completed successfully.
--> Executing Flake8 on files found in /home/testuser/testrole/postgres/molecule/default/tests/...
DEBUG: ANSIBLE ENVIRONMENT
--- {}

DEBUG: MOLECULE ENVIRONMENT
---
MOLECULE_DEBUG: 'True'
MOLECULE_DEPENDENCY_NAME: galaxy
MOLECULE_DRIVER_NAME: docker
MOLECULE_ENV_FILE: /home/testuser/testrole/postgres/.env.yml
MOLECULE_EPHEMERAL_DIRECTORY: /home/testuser/.cache/molecule/postgres/default
MOLECULE_FILE: /home/testuser/testrole/postgres/molecule/default/molecule.yml
MOLECULE_INSTANCE_CONFIG: /home/testuser/.cache/molecule/postgres/default/instance_config.yml
MOLECULE_INVENTORY_FILE: /home/testuser/.cache/molecule/postgres/default/inventory/ansible_inventory.yml
MOLECULE_LINT_NAME: yamllint
MOLECULE_PROJECT_DIRECTORY: /home/testuser/testrole/postgres
MOLECULE_PROVISIONER_LINT_NAME: ansible-lint
MOLECULE_PROVISIONER_NAME: ansible
MOLECULE_SCENARIO_DIRECTORY: /home/testuser/testrole/postgres/molecule/default
MOLECULE_SCENARIO_NAME: default
MOLECULE_STATE_FILE: /home/testuser/.cache/molecule/postgres/default/state.yml
MOLECULE_VERIFIER_LINT_NAME: flake8
MOLECULE_VERIFIER_NAME: testinfra
MOLECULE_VERIFIER_TEST_DIRECTORY: /home/testuser/testrole/postgres/molecule/default/tests

DEBUG: SHELL REPLAY
MOLECULE_DEBUG=True MOLECULE_DEPENDENCY_NAME=galaxy MOLECULE_DRIVER_NAME=docker MOLECULE_ENV_FILE=/home/testuser/testrole/postgres/.env.yml MOLECULE_EPHEMERAL_DIRECTORY=/home/testuser/.cache/molecule/postgres/default MOLECULE_FILE=/home/testuser/testrole/postgres/molecule/default/molecule.yml MOLECULE_INSTANCE_CONFIG=/home/testuser/.cache/molecule/postgres/default/instance_config.yml MOLECULE_INVENTORY_FILE=/home/testuser/.cache/molecule/postgres/default/inventory/ansible_inventory.yml MOLECULE_LINT_NAME=yamllint MOLECULE_PROJECT_DIRECTORY=/home/testuser/testrole/postgres MOLECULE_PROVISIONER_LINT_NAME=ansible-lint MOLECULE_PROVISIONER_NAME=ansible MOLECULE_SCENARIO_DIRECTORY=/home/testuser/testrole/postgres/molecule/default MOLECULE_SCENARIO_NAME=default MOLECULE_STATE_FILE=/home/testuser/.cache/molecule/postgres/default/state.yml MOLECULE_VERIFIER_LINT_NAME=flake8 MOLECULE_VERIFIER_NAME=testinfra MOLECULE_VERIFIER_TEST_DIRECTORY=/home/testuser/testrole/postgres/molecule/default/tests

DEBUG: COMMAND
/home/testuser/venv/bin/flake8 /home/testuser/testrole/postgres/molecule/default/tests/test_default.py

Lint completed successfully.
--> Executing Ansible Lint on /home/testuser/testrole/postgres/molecule/default/playbook.yml...
DEBUG: ANSIBLE ENVIRONMENT
---
ANSIBLE_CONFIG: /home/testuser/.cache/molecule/postgres/default/ansible.cfg
ANSIBLE_FILTER_PLUGINS: /home/testuser/venv/lib/python3.6/site-packages/molecule/provisioner/ansible/plugins/filters:/home/testuser/.cache/molecule/postgres/default/plugins/filters:/home/testuser/testrole/postgres/plugins/filters
ANSIBLE_LIBRARY: /home/testuser/venv/lib/python3.6/site-packages/molecule/provisioner/ansible/plugins/libraries:/home/testuser/.cache/molecule/postgres/default/library:/home/testuser/testrole/postgres/library
ANSIBLE_ROLES_PATH: /home/testuser/.cache/molecule/postgres/default/roles:/home/testuser/testrole

DEBUG: MOLECULE ENVIRONMENT
---
MOLECULE_DEBUG: 'True'
MOLECULE_DEPENDENCY_NAME: galaxy
MOLECULE_DRIVER_NAME: docker
MOLECULE_ENV_FILE: /home/testuser/testrole/postgres/.env.yml
MOLECULE_EPHEMERAL_DIRECTORY: /home/testuser/.cache/molecule/postgres/default
MOLECULE_FILE: /home/testuser/testrole/postgres/molecule/default/molecule.yml
MOLECULE_INSTANCE_CONFIG: /home/testuser/.cache/molecule/postgres/default/instance_config.yml
MOLECULE_INVENTORY_FILE: /home/testuser/.cache/molecule/postgres/default/inventory/ansible_inventory.yml
MOLECULE_LINT_NAME: yamllint
MOLECULE_PROJECT_DIRECTORY: /home/testuser/testrole/postgres
MOLECULE_PROVISIONER_LINT_NAME: ansible-lint
MOLECULE_PROVISIONER_NAME: ansible
MOLECULE_SCENARIO_DIRECTORY: /home/testuser/testrole/postgres/molecule/default
MOLECULE_SCENARIO_NAME: default
MOLECULE_STATE_FILE: /home/testuser/.cache/molecule/postgres/default/state.yml
MOLECULE_VERIFIER_LINT_NAME: flake8
MOLECULE_VERIFIER_NAME: testinfra
MOLECULE_VERIFIER_TEST_DIRECTORY: /home/testuser/testrole/postgres/molecule/default/tests

DEBUG: SHELL REPLAY
ANSIBLE_CONFIG=/home/testuser/.cache/molecule/postgres/default/ansible.cfg ANSIBLE_FILTER_PLUGINS=/home/testuser/venv/lib/python3.6/site-packages/molecule/provisioner/ansible/plugins/filters:/home/testuser/.cache/molecule/postgres/default/plugins/filters:/home/testuser/testrole/postgres/plugins/filters ANSIBLE_LIBRARY=/home/testuser/venv/lib/python3.6/site-packages/molecule/provisioner/ansible/plugins/libraries:/home/testuser/.cache/molecule/postgres/default/library:/home/testuser/testrole/postgres/library ANSIBLE_ROLES_PATH=/home/testuser/.cache/molecule/postgres/default/roles:/home/testuser/testrole MOLECULE_DEBUG=True MOLECULE_DEPENDENCY_NAME=galaxy MOLECULE_DRIVER_NAME=docker MOLECULE_ENV_FILE=/home/testuser/testrole/postgres/.env.yml MOLECULE_EPHEMERAL_DIRECTORY=/home/testuser/.cache/molecule/postgres/default MOLECULE_FILE=/home/testuser/testrole/postgres/molecule/default/molecule.yml MOLECULE_INSTANCE_CONFIG=/home/testuser/.cache/molecule/postgres/default/instance_config.yml MOLECULE_INVENTORY_FILE=/home/testuser/.cache/molecule/postgres/default/inventory/ansible_inventory.yml MOLECULE_LINT_NAME=yamllint MOLECULE_PROJECT_DIRECTORY=/home/testuser/testrole/postgres MOLECULE_PROVISIONER_LINT_NAME=ansible-lint MOLECULE_PROVISIONER_NAME=ansible MOLECULE_SCENARIO_DIRECTORY=/home/testuser/testrole/postgres/molecule/default MOLECULE_SCENARIO_NAME=default MOLECULE_STATE_FILE=/home/testuser/.cache/molecule/postgres/default/state.yml MOLECULE_VERIFIER_LINT_NAME=flake8 MOLECULE_VERIFIER_NAME=testinfra MOLECULE_VERIFIER_TEST_DIRECTORY=/home/testuser/testrole/postgres/molecule/default/tests

DEBUG: COMMAND
/home/testuser/venv/bin/ansible-lint -v --exclude=/home/testuser/.cache/molecule/postgres/default /home/testuser/testrole/postgres/molecule/default/playbook.yml

    Examining molecule/default/playbook.yml of type playbook
    Examining tasks/backup.yml of type tasks
    Examining tasks/centos_vars.yml of type tasks
Traceback (most recent call last):
  File "/home/testuser/venv/bin/ansible-lint", line 8, in <module>
    sys.exit(main())
  File "/home/testuser/venv/lib/python3.6/site-packages/ansiblelint/__main__.py", line 187, in main
    matches.extend(runner.run())
  File "/home/testuser/venv/lib/python3.6/site-packages/ansiblelint/__init__.py", line 287, in run
    skip_list=self.skip_list))
  File "/home/testuser/venv/lib/python3.6/site-packages/ansiblelint/__init__.py", line 177, in run
    matches.extend(rule.matchtasks(playbookfile, text))
  File "/home/testuser/venv/lib/python3.6/site-packages/ansiblelint/__init__.py", line 87, in matchtasks
    yaml = ansiblelint.utils.append_skipped_rules(yaml, text, file['type'])
  File "/home/testuser/venv/lib/python3.6/site-packages/ansiblelint/utils.py", line 596, in append_skipped_rules
    yaml_skip = _append_skipped_rules(pyyaml_data, file_text, file_type)
  File "/home/testuser/venv/lib/python3.6/site-packages/ansiblelint/utils.py", line 635, in _append_skipped_rules
    if pyyaml_task.get('name') != ruamel_task.get('name'):
AttributeError: 'AnsibleUnicode' object has no attribute 'get'
An error occurred during the test sequence action: 'lint'. Cleaning up.
--> Scenario: 'default'
--> Action: 'cleanup'
Skipping, cleanup playbook not configured.
--> Scenario: 'default'
--> Action: 'destroy'
--> Sanity checks: 'docker'
DEBUG: ANSIBLE ENVIRONMENT
---
ANSIBLE_CONFIG: /home/testuser/.cache/molecule/postgres/default/ansible.cfg
ANSIBLE_FILTER_PLUGINS: /home/testuser/venv/lib/python3.6/site-packages/molecule/provisioner/ansible/plugins/filters:/home/testuser/.cache/molecule/postgres/default/plugins/filters:/home/testuser/testrole/postgres/plugins/filters
ANSIBLE_LIBRARY: /home/testuser/venv/lib/python3.6/site-packages/molecule/provisioner/ansible/plugins/libraries:/home/testuser/.cache/molecule/postgres/default/library:/home/testuser/testrole/postgres/library
ANSIBLE_ROLES_PATH: /home/testuser/.cache/molecule/postgres/default/roles:/home/testuser/testrole

DEBUG: MOLECULE ENVIRONMENT
---
MOLECULE_DEBUG: 'True'
MOLECULE_DEPENDENCY_NAME: galaxy
MOLECULE_DRIVER_NAME: docker
MOLECULE_ENV_FILE: /home/testuser/testrole/postgres/.env.yml
MOLECULE_EPHEMERAL_DIRECTORY: /home/testuser/.cache/molecule/postgres/default
MOLECULE_FILE: /home/testuser/testrole/postgres/molecule/default/molecule.yml
MOLECULE_INSTANCE_CONFIG: /home/testuser/.cache/molecule/postgres/default/instance_config.yml
MOLECULE_INVENTORY_FILE: /home/testuser/.cache/molecule/postgres/default/inventory/ansible_inventory.yml
MOLECULE_LINT_NAME: yamllint
MOLECULE_PROJECT_DIRECTORY: /home/testuser/testrole/postgres
MOLECULE_PROVISIONER_LINT_NAME: ansible-lint
MOLECULE_PROVISIONER_NAME: ansible
MOLECULE_SCENARIO_DIRECTORY: /home/testuser/testrole/postgres/molecule/default
MOLECULE_SCENARIO_NAME: default
MOLECULE_STATE_FILE: /home/testuser/.cache/molecule/postgres/default/state.yml
MOLECULE_VERIFIER_LINT_NAME: flake8
MOLECULE_VERIFIER_NAME: testinfra
MOLECULE_VERIFIER_TEST_DIRECTORY: /home/testuser/testrole/postgres/molecule/default/tests

DEBUG: SHELL REPLAY
ANSIBLE_CONFIG=/home/testuser/.cache/molecule/postgres/default/ansible.cfg ANSIBLE_FILTER_PLUGINS=/home/testuser/venv/lib/python3.6/site-packages/molecule/provisioner/ansible/plugins/filters:/home/testuser/.cache/molecule/postgres/default/plugins/filters:/home/testuser/testrole/postgres/plugins/filters ANSIBLE_LIBRARY=/home/testuser/venv/lib/python3.6/site-packages/molecule/provisioner/ansible/plugins/libraries:/home/testuser/.cache/molecule/postgres/default/library:/home/testuser/testrole/postgres/library ANSIBLE_ROLES_PATH=/home/testuser/.cache/molecule/postgres/default/roles:/home/testuser/testrole MOLECULE_DEBUG=True MOLECULE_DEPENDENCY_NAME=galaxy MOLECULE_DRIVER_NAME=docker MOLECULE_ENV_FILE=/home/testuser/testrole/postgres/.env.yml MOLECULE_EPHEMERAL_DIRECTORY=/home/testuser/.cache/molecule/postgres/default MOLECULE_FILE=/home/testuser/testrole/postgres/molecule/default/molecule.yml MOLECULE_INSTANCE_CONFIG=/home/testuser/.cache/molecule/postgres/default/instance_config.yml MOLECULE_INVENTORY_FILE=/home/testuser/.cache/molecule/postgres/default/inventory/ansible_inventory.yml MOLECULE_LINT_NAME=yamllint MOLECULE_PROJECT_DIRECTORY=/home/testuser/testrole/postgres MOLECULE_PROVISIONER_LINT_NAME=ansible-lint MOLECULE_PROVISIONER_NAME=ansible MOLECULE_SCENARIO_DIRECTORY=/home/testuser/testrole/postgres/molecule/default MOLECULE_SCENARIO_NAME=default MOLECULE_STATE_FILE=/home/testuser/.cache/molecule/postgres/default/state.yml MOLECULE_VERIFIER_LINT_NAME=flake8 MOLECULE_VERIFIER_NAME=testinfra MOLECULE_VERIFIER_TEST_DIRECTORY=/home/testuser/testrole/postgres/molecule/default/tests

DEBUG: COMMAND
/home/testuser/venv/bin/ansible-playbook --skip-tags=molecule-notest,notest --diff --inventory=/home/testuser/.cache/molecule/postgres/default/inventory /home/testuser/venv/lib/python3.6/site-packages/molecule/provisioner/ansible/playbooks/docker/destroy.yml -vvv

    ansible-playbook 2.9.2
      config file = /home/testuser/.cache/molecule/postgres/default/ansible.cfg
      configured module search path = ['/home/testuser/venv/lib/python3.6/site-packages/molecule/provisioner/ansible/plugins/libraries', '/home/testuser/.cache/molecule/postgres/default/library', '/home/testuser/testrole/postgres/library']
      ansible python module location = /home/testuser/venv/lib/python3.6/site-packages/ansible
      executable location = /home/testuser/venv/bin/ansible-playbook
      python version = 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0]
    Using /home/testuser/.cache/molecule/postgres/default/ansible.cfg as config file
    host_list declined parsing /home/testuser/.cache/molecule/postgres/default/inventory/ansible_inventory.yml as it did not pass its verify_file() method
    script declined parsing /home/testuser/.cache/molecule/postgres/default/inventory/ansible_inventory.yml as it did not pass its verify_file() method
    Parsed /home/testuser/.cache/molecule/postgres/default/inventory/ansible_inventory.yml inventory source with yaml plugin

    PLAYBOOK: destroy.yml **********************************************************
    1 plays in /home/testuser/venv/lib/python3.6/site-packages/molecule/provisioner/ansible/playbooks/docker/destroy.yml

    PLAY [Destroy] *****************************************************************
    META: ran handlers

    TASK [Destroy molecule instance(s)] ********************************************
    task path: /home/testuser/venv/lib/python3.6/site-packages/molecule/provisioner/ansible/playbooks/docker/destroy.yml:8
    <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: testuser
    <127.0.0.1> EXEC /bin/sh -c 'echo ~testuser && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/testuser/.ansible/tmp/ansible-tmp-1576038266.5452287-224148635186079 `" && echo ansible-tmp-1576038266.5452287-224148635186079="` echo /home/testuser/.ansible/tmp/ansible-tmp-1576038266.5452287-224148635186079 `" ) && sleep 0'
    Using module file /home/testuser/venv/lib/python3.6/site-packages/ansible/modules/cloud/docker/docker_container.py
    <127.0.0.1> PUT /home/testuser/.ansible/tmp/ansible-local-5371w9gwap2n/tmpe4nyba9p TO /home/testuser/.ansible/tmp/ansible-tmp-1576038266.5452287-224148635186079/AnsiballZ_docker_container.py
    <127.0.0.1> PUT /home/testuser/.ansible/tmp/ansible-local-5371w9gwap2n/tmpfilu451r TO /home/testuser/.ansible/tmp/ansible-tmp-1576038266.5452287-224148635186079/async_wrapper.py
    <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/testuser/.ansible/tmp/ansible-tmp-1576038266.5452287-224148635186079/ /home/testuser/.ansible/tmp/ansible-tmp-1576038266.5452287-224148635186079/AnsiballZ_docker_container.py /home/testuser/.ansible/tmp/ansible-tmp-1576038266.5452287-224148635186079/async_wrapper.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c 'ANSIBLE_ASYNC_DIR='"'"'~/.ansible_async'"'"' /home/testuser/venv/bin/python /home/testuser/.ansible/tmp/ansible-tmp-1576038266.5452287-224148635186079/async_wrapper.py 364068843511 7200 /home/testuser/.ansible/tmp/ansible-tmp-1576038266.5452287-224148635186079/AnsiballZ_docker_container.py _ && sleep 0'
    changed: [localhost] => (item=postgres) => {
        "ansible_job_id": "364068843511.5397",
        "ansible_loop_var": "item",
        "changed": true,
        "finished": 0,
        "item": {
            "command": "/sbin/init",
            "env": {
                "http_proxy": null,
                "https_proxy": null,
                "no_proxy": null
            },
            "hostname": "postgres1",
            "image": "postgres",
            "name": "postgres",
            "pre_build_image": true,
            "previleged": true,
            "tmpfs": [
                "/run",
                "/tmp"
            ],
            "volumes": [
                "/sys/fs/cgroup:/sys/fs/cgroup:ro"
            ]
        },
        "results_file": "/home/testuser/.ansible_async/364068843511.5397",
        "started": 1
    }

    TASK [Wait for instance(s) deletion to complete] *******************************
    task path: /home/testuser/venv/lib/python3.6/site-packages/molecule/provisioner/ansible/playbooks/docker/destroy.yml:27
    <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: testuser
    <127.0.0.1> EXEC /bin/sh -c 'echo ~testuser && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/testuser/.ansible/tmp/ansible-tmp-1576038269.6703174-201026194839 `" && echo ansible-tmp-1576038269.6703174-201026194839="` echo /home/testuser/.ansible/tmp/ansible-tmp-1576038269.6703174-201026194839 `" ) && sleep 0'
    Using module file /home/testuser/venv/lib/python3.6/site-packages/ansible/modules/utilities/logic/async_status.py
    <127.0.0.1> PUT /home/testuser/.ansible/tmp/ansible-local-5371w9gwap2n/tmpaue7tqfm TO /home/testuser/.ansible/tmp/ansible-tmp-1576038269.6703174-201026194839/AnsiballZ_async_status.py
    <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/testuser/.ansible/tmp/ansible-tmp-1576038269.6703174-201026194839/ /home/testuser/.ansible/tmp/ansible-tmp-1576038269.6703174-201026194839/AnsiballZ_async_status.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '/home/testuser/venv/bin/python /home/testuser/.ansible/tmp/ansible-tmp-1576038269.6703174-201026194839/AnsiballZ_async_status.py && sleep 0'
    ok: [localhost] => (item={'started': 1, 'finished': 0, 'ansible_job_id': '364068843511.5397', 'results_file': '/home/testuser/.ansible_async/364068843511.5397', 'changed': True, 'failed': False, 'item': {'name': 'postgres', 'image': 'postgres', 'hostname': 'postgres1', 'env': {'http_proxy': None, 'https_proxy': None, 'no_proxy': None}, 'command': '/sbin/init', 'tmpfs': ['/run', '/tmp'], 'volumes': ['/sys/fs/cgroup:/sys/fs/cgroup:ro'], 'previleged': True, 'pre_build_image': True}, 'ansible_loop_var': 'item'}) => {
        "ansible_job_id": "364068843511.5397",
        "ansible_loop_var": "item",
        "attempts": 1,
        "changed": false,
        "diff": {
            "after": {},
            "before": {}
        },
        "finished": 1,
        "invocation": {
            "module_args": {
                "api_version": "auto",
                "auto_remove": false,
                "blkio_weight": null,
                "ca_cert": null,
                "cap_drop": null,
                "capabilities": null,
                "cleanup": false,
                "client_cert": null,
                "client_key": null,
                "command": null,
                "comparisons": null,
                "cpu_period": null,
                "cpu_quota": null,
                "cpu_shares": null,
                "cpuset_cpus": null,
                "cpuset_mems": null,
                "debug": false,
                "detach": true,
                "device_read_bps": null,
                "device_read_iops": null,
                "device_write_bps": null,
                "device_write_iops": null,
                "devices": null,
                "dns_opts": null,
                "dns_search_domains": null,
                "dns_servers": null,
                "docker_host": "localhost:2375",
                "domainname": null,
                "entrypoint": null,
                "env": null,
                "env_file": null,
                "etc_hosts": null,
                "exposed_ports": null,
                "force_kill": true,
                "groups": null,
                "healthcheck": null,
                "hostname": null,
                "ignore_image": false,
                "image": null,
                "init": false,
                "interactive": false,
                "ipc_mode": null,
                "keep_volumes": true,
                "kernel_memory": null,
                "kill_signal": null,
                "labels": null,
                "links": null,
                "log_driver": null,
                "log_options": null,
                "mac_address": null,
                "memory": "0",
                "memory_reservation": null,
                "memory_swap": null,
                "memory_swappiness": null,
                "mounts": null,
                "name": "postgres",
                "network_mode": null,
                "networks": null,
                "networks_cli_compatible": null,
                "oom_killer": null,
                "oom_score_adj": null,
                "output_logs": false,
                "paused": false,
                "pid_mode": null,
                "pids_limit": null,
                "privileged": false,
                "published_ports": null,
                "pull": false,
                "purge_networks": false,
                "read_only": false,
                "recreate": false,
                "restart": false,
                "restart_policy": null,
                "restart_retries": null,
                "runtime": null,
                "security_opts": null,
                "shm_size": null,
                "ssl_version": null,
                "state": "absent",
                "stop_signal": null,
                "stop_timeout": null,
                "sysctls": null,
                "timeout": 60,
                "tls": false,
                "tls_hostname": "localhost",
                "tls_verify": false,
                "tmpfs": null,
                "trust_image_content": false,
                "tty": false,
                "ulimits": null,
                "user": null,
                "userns_mode": null,
                "uts": null,
                "validate_certs": false,
                "volume_driver": null,
                "volumes": null,
                "volumes_from": null,
                "working_dir": null
            }
        },
        "item": {
            "ansible_job_id": "364068843511.5397",
            "ansible_loop_var": "item",
            "changed": true,
            "failed": false,
            "finished": 0,
            "item": {
                "command": "/sbin/init",
                "env": {
                    "http_proxy": null,
                    "https_proxy": null,
                    "no_proxy": null
                },
                "hostname": "postgres1",
                "image": "postgres",
                "name": "postgres",
                "pre_build_image": true,
                "previleged": true,
                "tmpfs": [
                    "/run",
                    "/tmp"
                ],
                "volumes": [
                    "/sys/fs/cgroup:/sys/fs/cgroup:ro"
                ]
            },
            "results_file": "/home/testuser/.ansible_async/364068843511.5397",
            "started": 1
        }
    }

    TASK [Delete docker network(s)] ************************************************
    task path: /home/testuser/venv/lib/python3.6/site-packages/molecule/provisioner/ansible/playbooks/docker/destroy.yml:35
    META: ran handlers
    META: ran handlers

    PLAY RECAP *********************************************************************
    localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
```

**Comment by ssbarnea** [comment]
I think is clear from the output that the error does to come from molecule itself but from ansible-lint.
