### ISSUE TITLE
macOS Catalina

### ISSUE THREAD

**Issue by netgain-justin-trantham** [ansible/molecule#2485]
Hey all,

I've been having some terrible issues getting molecule to work properly as it was before I got a new laptop on Catalina.

Below is what I get when just running a simple molecule create

`--> Validating schema /Users/justintrantham/git/ansible/roles/malwarebytes-scan/molecule/default/molecule.yml.
Validation completed successfully.
--> Test matrix
    
└── default
    ├── dependency
    ├── create
    └── prepare
    
--> Scenario: 'default'
--> Action: 'dependency'
Skipping, missing the requirements file.
--> Scenario: 'default'
--> Action: 'create'
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/Users/justintrantham/Library/Python/3.7/lib/python/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/justintrantham/Library/Python/3.7/lib/python/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/justintrantham/Library/Python/3.7/lib/python/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/justintrantham/Library/Python/3.7/lib/python/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/justintrantham/Library/Python/3.7/lib/python/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/justintrantham/Library/Python/3.7/lib/python/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/molecule/command/create.py", line 117, in create
    base.execute_cmdline_scenarios(scenario_name, args, command_args)
  File "/usr/local/lib/python3.7/site-packages/molecule/command/base.py", line 98, in execute_cmdline_scenarios
    execute_scenario(scenario)
  File "/usr/local/lib/python3.7/site-packages/molecule/command/base.py", line 141, in execute_scenario
    execute_subcommand(scenario.config, action)
  File "/usr/local/lib/python3.7/site-packages/molecule/command/base.py", line 128, in execute_subcommand
    return command(config).execute()
  File "/usr/local/lib/python3.7/site-packages/molecule/command/create.py", line 90, in execute
    self._config.provisioner.create()
  File "/usr/local/lib/python3.7/site-packages/molecule/provisioner/ansible.py", line 700, in create
    pb.execute()
  File "/usr/local/lib/python3.7/site-packages/molecule/provisioner/ansible_playbook.py", line 92, in execute
    self.bake()
  File "/usr/local/lib/python3.7/site-packages/molecule/provisioner/ansible_playbook.py", line 67, in bake
    self._ansible_command = sh.ansible_playbook.bake(
  File "/Users/justintrantham/Library/Python/3.7/lib/python/site-packages/sh.py", line 3349, in __getattr__
    return self.__env[name]
  File "/Users/justintrantham/Library/Python/3.7/lib/python/site-packages/sh.py", line 3226, in __getitem__
    raise CommandNotFound(k)
sh.CommandNotFound: ansible_playbook
`

**Comment by netgain-justin-trantham** [comment]
Disregard will update if more come of this still troubleshooting
