### ISSUE TITLE
molecule login does not work with podman containers

### ISSUE THREAD

**Issue by brandor5** [ansible/molecule#4057]
### Prerequisites

- [X] This was not already reported in the past (duplicate check)
- [X] It does reproduce it with code from main branch (latest unreleased version)
- [X] I include a minimal example for reproducing the bug
- [X] The bug is not trivial, as for those a direct pull-request is preferred
- [X] Running `pip check` does not report any conflicts
- [X] I was able to reproduce the issue on a different machine
- [X] The issue is not specific to any driver other than 'default' one

### Environment

$ molecule --version
molecule 6.0.2 using python 3.9 
    ansible:2.15.4
    default:6.0.2 from molecule

$ rpm -q python3
python3-3.9.16-1.el9_2.1.x86_64

$ rpm -q ansible-core 
ansible-core-2.15.4-1.el9ap.noarch

$ rpm -q molecule 
molecule-6.0.2-1.el9ap.noarch

$ cat /etc/redhat-release 
Red Hat Enterprise Linux release 9.2 (Plow)

### What happened

I followed the Red Hat blog [0] example and then followed the docs [1] to enable podman containers. Everything appeared to work, however when I tried to `molecule login -h ubi8` I received the following error:

~~~
$ molecule login -h ubi8
INFO     Running default > login
Traceback (most recent call last):
  File "/usr/bin/molecule", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.9/site-packages/molecule/command/login.py", line 129, in login
    base.execute_subcommand(scenario.config, subcommand)
  File "/usr/lib/python3.9/site-packages/molecule/command/base.py", line 156, in execute_subcommand
    return command(config).execute(args)
  File "/usr/lib/python3.9/site-packages/molecule/logger.py", line 189, in wrapper
    rt = func(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/molecule/command/login.py", line 56, in execute
    self._get_login(hostname)
  File "/usr/lib/python3.9/site-packages/molecule/command/login.py", line 96, in _get_login
    login_options = self._config.driver.login_options(hostname)
  File "/usr/lib/python3.9/site-packages/molecule/driver/delegated.py", line 195, in login_options
    return util.merge_dicts(d, self._get_instance_config(instance_name))
  File "/usr/lib/python3.9/site-packages/molecule/driver/delegated.py", line 250, in _get_instance_config
    instance_config_dict = util.safe_load_file(self._config.driver.instance_config)
  File "/usr/lib/python3.9/site-packages/molecule/util.py", line 245, in safe_load_file
    with open(filename) as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/brandor5/.cache/molecule/extensions/default/instance_config.yml'
~~~

I can workaround the problem by modifying molecule.yml to include the following:

~~~
driver:
  options:
    managed: False
    login_cmd_template: 'podman exec -ti {instance} bash'
    ansible_connection_options:
      ansible_connection: podman
~~~

[0] https://developers.redhat.com/articles/2023/09/13/introducing-ansible-molecule-ansible-automation-platform
[1] https://ansible.readthedocs.io/projects/molecule/podman/

### Reproducing example

```yml
---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml

platforms:
  - name: ubi8
    image: registry.access.redhat.com/ubi8/ubi-init:latest
  - name: ubi9
    image: registry.access.redhat.com/ubi9/ubi-init:latest

provisioner:
  name: ansible
  config_options:
    defaults:
      collections_path: ${ANSIBLE_COLLECTIONS_PATH}
```

**Comment by ssbarnea** [comment]
PR would be welcomed here.

**Comment by brandor5** [comment]
Will work on getting that put in. Thanks!
